//
//  RobotStyleKit.h
//  TableExample
//
//  Created by Ryan Bigger on 9/8/17.
//  Copyright © 2017 Ryan Bigger. All rights reserved.
//
//  Generated by PaintCode
//  http://www.paintcodeapp.com
//

#import <UIKit/UIKit.h>



typedef enum : NSInteger
{
    RobotStyleKitResizingBehaviorAspectFit, //!< The content is proportionally resized to fit into the target rectangle.
    RobotStyleKitResizingBehaviorAspectFill, //!< The content is proportionally resized to completely fill the target rectangle.
    RobotStyleKitResizingBehaviorStretch, //!< The content is stretched to match the entire target rectangle.
    RobotStyleKitResizingBehaviorCenter, //!< The content is centered in the target rectangle, but it is NOT resized.

} RobotStyleKitResizingBehavior;

extern CGRect RobotStyleKitResizingBehaviorApply(RobotStyleKitResizingBehavior behavior, CGRect rect, CGRect target);


@interface RobotStyleKit : NSObject

// Drawing Methods
+ (void)drawRobot;
+ (void)drawRobotWithFrame: (CGRect)targetFrame resizing: (RobotStyleKitResizingBehavior)resizing;

@end
